version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - db_data:${DB_VOLUME}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app-network
    
  pgadmin:
      image: dpage/pgadmin4
      volumes:
        - pgadmin_data:${PGADMIN_VOLUME}
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - "${PGADMIN_PORT}:80"
      depends_on:
        - postgres
      networks:
        - app-network

  # node-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USERNAME: me
  #     DB_PASSWORD: root
  #     DB_NAME: note_taking_app
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db_data:
  pgadmin_data: