################################# NOTES TESTS ##########################################
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxNzAwNjQ4MiwiZXhwIjoxNzE3NjExMjgyfQ.wHgVNuyBnb9rrlXVqbpDwJvyr4iHBbO003QI7UOfwtk
### Create a Note  //WORKING

POST http://localhost:3000/notes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "abel note 1 title",
    "body": "abel note 1 content."
}

### Get all notes.  //WORKING
GET http://localhost:8080/notes
Authorization: Bearer {{token}}

### Get a note by id. //WORKING
GET http://localhost:3000/notes/52
Authorization: Bearer {{token}}


### Update a note.  //WORKING
PUT http://localhost:3000/notes/57
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "This is the 1.",
    "body": "This is the body 1."
}

### Delete a note. //WORKING
DELETE http://localhost:3000/notes/52
Authorization: Bearer {{token}}



################################### USER TESTS ########################################

### Create user.  //WORKING
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "abel",
    "password": "12345678"
}


### Login user  //
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "abel",
    "password": "12345678"
}

### Logout user
POST http://localhost:3000/auth/logout
Authorization: Bearer {{token}}




#### user-Profile ####
GET http://localhost:8080/user//user-Profile
Authorization: Bearer {{token}}

